### ISSUE TITLE
CLI Tools

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#12]
These tools would allow me to:

- [x] Upload files to 3Blades, specially large ones (more than 100Mb and up to a few Gb)
- [x] Create and control de lifecycle of servers (models/jobs/workspaces/datasources)
- [x] Consult model/job execution data (e.g. model or job execution log and stats)

The CLI tools should:

- Provide authentication mechanisms (i.e., key id and secret key)
- Easy to install (pip install ..., brew install ..., etc)
- Perform automatic checks for updates, prompting the user when an update is ready.

## Implementation notes

Several choices are available for CLI Tools. Wither Python or Golang are good choices. However, Golang may be a better choice since the compiled binary could run on target O/S without having to install additional dependencies.

**Comment by jkp85** [comment]
Large files are not yet implemented.
For authentication currently simple api token is used. However in my opinion we need to implement JWT on all servers.

**Comment by jgwerner** [comment]
Done.
