### ISSUE TITLE
Audit Libraries Included as Requirements

### ISSUE THREAD

**Issue by johngriebel** [3Blades/3blades#121]
We need to ensure that the external libraries we are using have licenses that are BSD-3 compatible across all repositories.

- [x] [app-backend](https://github.com/3Blades/app-backend/issues/315)
- [x] [cli-tools](https://github.com/3Blades/cli-tools/issues/116)
- [x] [go-sdk](https://github.com/3Blades/go-sdk/issues/35)
- [x] [react-frontend](https://github.com/3Blades/react-frontend/issues/198)
- [x] [core-server](https://github.com/3Blades/core-server/issues/26)
- [x] [openapi](https://github.com/3Blades/openapi/issues/127)
- [x] [openresty](https://github.com/3Blades/openresty/issues/49)
- [x] Internal Repos

**Comment by johngriebel** [comment]
Done. We should consider creating automated checks for these in the future.
