### ISSUE TITLE
Version control of user files with git.

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#15]
All files in every project should be version controlled. We should use git. Proposing these phases:

- [ ] Phase 1. For every new project, a local Git repo is created.
- [ ] Phase 2. Allow forking of all public projects, or your private projects where user is owner or collaborator.
- [ ] Phase 3. Users will be able to upload changes of their local project to a Git hosting service. Will implement this first with Github, but will be open to integrate BitBucket and Gitlab. A `Save` button would trigger a `git commit -a -m "commit message"` and `git push origin <branch>`.
- [ ] Phase 4. Support additional git integration features, such as submitting PR, creating local branches, etc.

**Comment by johngriebel** [comment]
closing due to age.
