### ISSUE TITLE
Plans for version 1.0 backend

### ISSUE THREAD

**Issue by jkp85** [3Blades/3blades#8]
app-backend migration to django (RESTful):
- [x] project config
- [x] migrating models from sqlalchemy to django
- [x] database migration
- [x] project endpoints
- [x] server endpoints
- [x] user endpoints
- [x] OAuth2 endpoints
- [ ] integrations
- [x] actions
- [ ] events
- [x] triggers 

stream-api:
- [x] server logs (this is handled by logspout but we probably need to replace it)
- [ ] actions
- [ ] events

core-server:
- [x] refactor not to use database and redis urls but only api endpoint and key

**Comment by jgwerner** [comment]
@jkp85 the piece missing is integrations with GitHub, AWS and Google Drive correct?

**Comment by jkp85** [comment]
@jgwerner correct

**Comment by jgwerner** [comment]
@johngriebel @jkp85 lets review this list tomorrow.

**Comment by jgwerner** [comment]
No longer applicable.
