### ISSUE TITLE
Add WSGI compatible web server as create option

### ISSUE THREAD

**Issue by jgwerner** [3Blades/3blades#9]
One of our users would like to publish information via a web app. This information could include tables and/or visualizations catered for the business user.

Right now the user uses a local Notebook server instance and launches a Flask application directly from the Notebook console using Flask. We would like to enable any WSGI compatible servers (Pyramid, Flask, Django, etc) and use the current infrastructure with core-server that has been set in place. In the beginning we could start with just Flask. A simple web app would be launched as:

```
from flask import Flask
app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Flask Dockerized'

if __name__ == '__main__':
    app.run(debug=True,host='0.0.0.0')
```

The Dockerfile should have a `CMD` that uses the Golang runner/server binary to set argument values, such as `start-webapp.sh`.  This bash file could have a command similar to one of the other child server types, such as:

```
/serve -db="postgresql://user:password@db-production2.myinstance.us-west-2.rds.amazonaws.com/mydb?sslmode=require" \ 
-redis="redis://production.myinstance.0001.usw2.cache.amazonaws.com:6379/0" \
-hashid="{webapp.hashid}" \
-port=5000 \
-resource="/home/work" \
python /usr/local/bin/run.py
```

We would need to add a new table to the model, to reflect new child server type (webapp).

We would also need to add a new views with Jinja2 (for both users and admin), to allow the user to launch webapp containers.

TODO: add wire frame

@AbhishikthaReddy will take the lead on this.

**Comment by netoisc** [comment]
I just worked in a workaround in our current on-premise version to allow launching a web-app. And I think it can be very useful to complete this.
First, I created a env-type called *web-app* similar to jupyter-lab (it could be whatever core-server based ), the most important part is the CMD. It does not contain `jupyter` as the executable, it use `python3 run.py` instead of.
Second, there is a functionality to install dependencies within server (model/worskpace/job) in the launch time, it's called *Startup script*, and with this you can install python dependencies, like Flask. In my case i created a file `dependencies.sh` with the content:

`pip3 install flask`

Finally and having in mind that we can launch containers if them expose a port and listen on the  `/container/<server.hashid>` endpoint (the nginx will forward the outside traffic to it), i created a file called `run.py` with a simple flask-app by using a *blueprint* (it really was the trick) to follow that url convention , the full code is:
```from flask import Flask,  Blueprint
from os import environ
app = Flask(__name__)

# app.config["APPLICATION_ROOT"] = environ.get('APPLICATION_ROOT')
prefix = environ.get('APPLICATION_ROOT')
app.config["DEBUG"] = True

bp = Blueprint('web-app-behind-nginx', __name__)


@bp.route("/")
def main():
    return "Welcome!"

# register blueprint
app.register_blueprint(bp, url_prefix=prefix)

if __name__ == '__main__':
    print(prefix)
    app.run(host='0.0.0.0') 
```

With all above i think that we only have to work with:
 - repo: `3blades/notebook-servers`: Build/create a new image, base it on the Golang runner/server (as Greg said/made) but simplify it by installing only the dependencies needed and include the flask package.
 - repo: `3blades/hubserver`:

    - [ ] Create a new *type* in the TypeMixin model 
    - [ ] modify the _layout-sidebar.html template to add the new item *Web app*
    - [ ] Add the templates to allow the user creating web apps and list them (you can see models or workspaces folder) 


_For_ the on-premise version it will be need modify the ansible script to create the new *env-type* automatically_

**Comment by jgwerner** [comment]
Duplicate of #18
